import { startTransition, useDeferredValue, useEffect, useMemo, useState, type ReactNode } from 'react'
import { BrowserRouter, Link, Route, Routes, useLocation, useNavigate, useParams } from 'react-router-dom'
import { ArrowRight, Check, ChevronRight, CircleHelp, FileText, Flag, Gauge, LayoutDashboard, Library, Menu, MessageSquare, Plus, Search, ShieldCheck, Sparkles, X } from 'lucide-react'
import { api } from './api'
import type { Answer, Comparison, Document } from './types'
import './App.css'
import './accessibility.css'

const demoId = 'demo-rental-v1'
const tabs = [['overview', 'Overview'], ['clauses', 'Clause explorer'], ['obligations', 'Obligations'], ['flags', 'Attention flags'], ['chat', 'Ask the document']] as const

function Feedback({ message, retry }: { message: string; retry?: () => void }) {
  return <div className="feedback" role="alert"><p>{message}</p>{retry && <button className="button secondary" onClick={retry}>Try again</button>}</div>
}

function Shell({ children }: { children: ReactNode }) {
  const location = useLocation()
  const [open, setOpen] = useState(false)
  const nav = [{ to: '/app', label: 'Overview', icon: LayoutDashboard }, { to: `/app/documents/${demoId}`, label: 'Documents', icon: Library }, { to: '/app/compare', label: 'Compare', icon: Gauge }, { to: '/app/settings', label: 'Settings', icon: ShieldCheck }]
  return <div className="app-shell"><aside className={open ? 'sidebar open' : 'sidebar'}><div className="brand"><span className="brand-mark"><Sparkles size={16} aria-hidden="true" /></span><b>Nyaya<span>Lens</span></b><button className="icon-button close-mobile" onClick={() => setOpen(false)} aria-label="Close navigation"><X size={18} /></button></div><div className="demo-pill"><i /> Demo workspace</div><nav aria-label="Primary navigation">{nav.map(item => <Link key={item.to} className={location.pathname === item.to || (item.label === 'Documents' && location.pathname.includes('/documents/')) ? 'nav-item active' : 'nav-item'} to={item.to} onClick={() => setOpen(false)}><item.icon size={18} aria-hidden="true" />{item.label}</Link>)}</nav><div className="sidebar-bottom"><div className="privacy-note"><ShieldCheck size={17} aria-hidden="true" /><div><b>Private by design</b><span>Your demo data stays local.</span></div></div><div className="profile"><span className="avatar">JL</span><div><b>Jordan Lee</b><span>Demo account</span></div><ChevronRight size={16} aria-hidden="true" /></div></div></aside><main className="main"><header className="topbar"><button className="icon-button menu-button" onClick={() => setOpen(true)} aria-label="Open navigation"><Menu size={20} /></button><div className="breadcrumbs">Workspace <ChevronRight size={14} aria-hidden="true" /> <span>{location.pathname.includes('documents') ? 'Document workspace' : location.pathname.includes('compare') ? 'Compare' : 'Overview'}</span></div><div className="top-actions"><span className="top-status"><i /> Demo mode</span><span className="help-button"><CircleHelp size={17} aria-hidden="true" /> Help</span></div></header><div className="content">{children}</div></main></div>
}

function PageTitle({ eyebrow, title, copy, action }: { eyebrow: string; title: string; copy: string; action?: ReactNode }) { return <div className="page-title"><div><span className="section-label">{eyebrow}</span><h1>{title}</h1><p>{copy}</p></div>{action}</div> }
function Empty({ title, copy }: { title: string; copy: string }) { return <div className="empty-state"><span className="chat-icon"><FileText size={22} aria-hidden="true" /></span><h2>{title}</h2><p>{copy}</p><Link to="/app" className="button primary">Back to workspace</Link></div> }

function Dashboard() {
  const [docs, setDocs] = useState<Document[]>([])
  const [state, setState] = useState<'loading' | 'ready' | 'error'>('loading')
  const load = () => { setState('loading'); api.documents().then(value => { setDocs(value); setState('ready') }).catch(() => setState('error')) }
  useEffect(load, [])
  return <><PageTitle eyebrow="Workspace" title="Good morning, Jordan." copy="Make the next document conversation a little clearer." action={<Link to="/app/documents/new" className="button primary"><Plus size={17} aria-hidden="true" /> Analyze document</Link>} /><div className="dashboard-grid"><section className="main-column"><div className="section-heading"><div><span className="section-label">Your documents</span><h2>Recent analysis</h2></div><span className="subtle-button"><Search size={16} aria-hidden="true" /> Search</span></div>{state === 'loading' && <div className="loading-state" role="status"><span className="loader" /> Loading your documents...</div>}{state === 'error' && <Feedback message="Your documents could not be loaded." retry={load} />}{state === 'ready' && docs.length === 0 && <div className="empty-panel"><h3>No documents yet</h3><p>Upload a PDF or DOCX to begin a source-backed review.</p><Link to="/app/documents/new" className="button secondary">Analyze a document <ArrowRight size={16} /></Link></div>}{state === 'ready' && <div className="doc-list">{docs.map(doc => <Link to={`/app/documents/${doc.id}`} className="document-row" key={doc.id}><span className="file-icon"><FileText size={20} aria-hidden="true" /></span><span className="doc-info"><b>{doc.name}</b><span>{doc.type} · {doc.pages} pages</span></span><span className="doc-status"><i />{doc.status}</span><span className="doc-date">{doc.updated_at}</span><ChevronRight size={17} aria-hidden="true" /></Link>)}</div>}<div className="sample-banner"><div className="sample-mark"><Sparkles size={19} aria-hidden="true" /></div><div><span className="section-label">Start with a sample</span><b>See NyayaLens in action</b><p>Explore a fictional rental agreement with grounded answers and questions.</p></div><Link to={`/app/documents/${demoId}`} className="icon-button filled" aria-label="Open sample agreement"><ArrowRight size={18} /></Link></div></section><aside className="side-column"><div className="side-card"><span className="section-label">A useful distinction</span><h3>Facts first. Interpretation second.</h3><p>Every answer labels what is explicit in the document versus what deserves a closer look.</p></div></aside></div></>
}

function PanelHeading({ label, title }: { label: string; title: string }) { return <div className="panel-heading"><span className="section-label">{label}</span><h2>{title}</h2></div> }
function OverviewPanel({ doc, selectFlags }: { doc: Document; selectFlags: () => void }) { return <><PanelHeading label="Document overview" title="What this agreement says" /><div className="summary-box"><p>{doc.overview.summary}</p><span><Sparkles size={14} aria-hidden="true" /> {doc.is_demo ? 'Fixture-backed analysis' : 'Text extracted from upload'}</span></div><div className="facts-grid">{[['Parties', doc.overview.parties.join(' · ') || 'Not identified'], ['Effective date', doc.overview.effective_date], ['Duration', doc.overview.duration], ['Jurisdiction', doc.overview.jurisdiction]].map(([label, value]) => <div className="fact" key={label}><span>{label}</span><b>{value}</b><small>Source: document text</small></div>)}</div><div className="limitations"><h3>Read with care</h3>{doc.overview.limitations.map(item => <p key={item}><Check size={14} aria-hidden="true" />{item}</p>)}</div><div className="next-card"><div><span className="section-label">Suggested next step</span><b>Review the attention flags</b><p>{doc.flags.length ? `${doc.flags.length} places may need a follow-up question.` : 'No structured attention flags were generated for this upload.'}</p></div><button className="icon-button filled" onClick={selectFlags} aria-label="Review attention flags"><ArrowRight size={17} /></button></div></> }
function ClausePanel({ clauses, query, setQuery }: { clauses: Document['clauses']; query: string; setQuery: (value: string) => void }) { return <><PanelHeading label="Clause explorer" title="Find the fine print" /><div className="search-field"><Search size={16} aria-hidden="true" /><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Search clauses" aria-label="Search clauses" /></div>{clauses.length === 0 ? <div className="empty-panel"><h3>No matching clauses</h3><p>Try a broader search term.</p></div> : <div className="clause-list">{clauses.map(clause => <article className="clause-card" id={clause.id} key={clause.id}><div><span className="category-tag">{clause.category}</span><h3>{clause.heading}</h3><p>{clause.text}</p></div><span className="page-link">p. {clause.page}</span></article>)}</div>}</> }
function ObligationPanel({ doc }: { doc: Document }) { return <><PanelHeading label="Obligation tracker" title="Who needs to do what" />{doc.obligations.length ? <div className="obligation-list">{doc.obligations.map(item => <article className="obligation" key={item.id}><div className="obligation-top"><span className="party-tag">{item.party}</span><span className="certainty">{item.certainty}</span></div><h3>{item.action}</h3><div className="obligation-detail"><span>Trigger</span><b>{item.trigger}</b></div>{item.amount && <div className="obligation-detail"><span>Amount</span><b>{item.amount}</b></div>}<a href={`#${item.clause_id}`} className="source-link">Source: {item.clause_id.split('-').pop()}</a></article>)}</div> : <div className="empty-panel"><h3>No structured obligations</h3><p>This upload has extracted text but has not received structured analysis.</p></div>}</> }
function FlagPanel({ doc }: { doc: Document }) { return <><PanelHeading label="Attention flags" title="Worth a closer look" /><p className="panel-intro">These are textual observations, not legal conclusions.</p>{doc.flags.length ? <div className="flag-list">{doc.flags.map(flag => <article className="flag-card" key={flag.id}><div className="flag-head"><span className="flag-icon"><Flag size={16} aria-hidden="true" /></span><div><span className="flag-kind">{flag.kind}</span><h3>{flag.title}</h3></div></div><p>{flag.explanation}</p><div className="why"><b>Why investigate</b><span>{flag.why}</span></div><div className="question"><MessageSquare size={15} aria-hidden="true" /><span>{flag.question}</span></div><a href={`#${flag.clause_ids[0]}`} className="source-link">Source: {flag.clause_ids.join(', ')}</a></article>)}</div> : <div className="empty-panel"><h3>No attention flags</h3><p>There are no structured flags for this extracted upload.</p></div>}</> }
function ChatPanel({ doc, answer, loading, error, ask }: { doc: Document; answer: Answer | null; loading: boolean; error: string; ask: (question: string) => void }) { const [value, setValue] = useState(''); const examples = ['What payments am I required to make?', 'When can either party terminate?', 'Does the agreement mention renewal?']; return <><PanelHeading label="Document-grounded chat" title="Ask the agreement" /><div className="chat-notice"><ShieldCheck size={16} aria-hidden="true" /><span>Answers are limited to this document and cite source clauses.</span></div>{error && <Feedback message={error} /> }<div className="chat-body">{!answer && !loading && <div className="chat-empty"><span className="chat-icon"><MessageSquare size={20} aria-hidden="true" /></span><h3>What would you like to find?</h3><p>Try one of these questions.</p><div className="suggestions">{examples.map(example => <button key={example} onClick={() => ask(example)}>{example}<ArrowRight size={14} aria-hidden="true" /></button>)}</div></div>}{loading && <div className="loading-state" role="status"><span className="loader" /> Checking the document...</div>}{answer && <div className="answer"><span className={answer.supported ? 'answer-label supported' : 'answer-label'}>{answer.supported ? 'Supported by document' : 'Not enough evidence'}</span><p className="answer-main">{answer.answer}</p><div className="answer-block"><b>Direct facts</b><p>{answer.direct_facts}</p></div><div className="answer-block"><b>Interpretation</b><p>{answer.interpretation}</p></div>{answer.citations.length > 0 && <div className="citations"><b>Sources</b>{answer.citations.map(citation => <a href={`#${citation.clause_id}`} key={citation.clause_id}><span>p. {citation.page}</span>{citation.clause_id}</a>)}</div>}</div>}</div><form className="chat-form" onSubmit={event => { event.preventDefault(); if (value.trim()) { ask(value.trim()); setValue('') } }}><input value={value} onChange={event => setValue(event.target.value)} placeholder="Ask about this document..." aria-label="Ask about this document" /><button className="button primary" type="submit" disabled={loading} aria-label="Ask question"><ArrowRight size={17} /></button></form></> }

function Workspace() {
  const { documentId = demoId } = useParams()
  const [doc, setDoc] = useState<Document | null>(null)
  const [status, setStatus] = useState<'loading' | 'ready' | 'error'>('loading')
  const [tab, setTab] = useState<(typeof tabs)[number][0]>('overview')
  const [query, setQuery] = useState('')
  const [answer, setAnswer] = useState<Answer | null>(null)
  const [questionLoading, setQuestionLoading] = useState(false)
  const [questionError, setQuestionError] = useState('')
  const load = () => { setStatus('loading'); api.document(documentId).then(value => { setDoc(value); setStatus('ready') }).catch(() => setStatus('error')) }
  useEffect(load, [documentId])
  const deferredQuery = useDeferredValue(query)
  const clauses = useMemo(() => doc?.clauses.filter(clause => `${clause.heading} ${clause.text} ${clause.category}`.toLowerCase().includes(deferredQuery.toLowerCase())) ?? [], [doc, deferredQuery])
  if (status === 'loading') return <div className="loading-state" role="status"><span className="loader" /> Loading document...</div>
  if (status === 'error' || !doc) return <Feedback message="This document could not be loaded." retry={load} />
  const ask = async (question: string) => { setQuestionLoading(true); setQuestionError(''); setAnswer(null); try { setAnswer(await api.question(doc.id, question)) } catch (error) { setQuestionError(error instanceof Error ? error.message : 'The question could not be answered.') } finally { setQuestionLoading(false) } }
  return <><div className="workspace-heading"><div><Link to="/app" className="back-link"><ChevronRight size={15} className="rotate" aria-hidden="true" /> All documents</Link><h1>{doc.name}</h1><div className="doc-meta"><span className="status-chip"><Check size={13} aria-hidden="true" /> {doc.status}</span><span>{doc.type}</span><span>{doc.pages} pages</span><span>Updated {doc.updated_at}</span></div></div></div><div className="workspace-tabs" role="tablist" aria-label="Document views">{tabs.map(([value, label]) => <button key={value} role="tab" aria-selected={tab === value} aria-controls={`panel-${value}`} id={`tab-${value}`} className={tab === value ? 'active' : ''} onClick={() => startTransition(() => setTab(value))}>{label}</button>)}</div><section className="workspace-panel" role="tabpanel" id={`panel-${tab}`} aria-labelledby={`tab-${tab}`}>{tab === 'overview' && <OverviewPanel doc={doc} selectFlags={() => startTransition(() => setTab('flags'))} />}{tab === 'clauses' && <ClausePanel clauses={clauses} query={query} setQuery={setQuery} />}{tab === 'obligations' && <ObligationPanel doc={doc} />}{tab === 'flags' && <FlagPanel doc={doc} />}{tab === 'chat' && <ChatPanel doc={doc} answer={answer} loading={questionLoading} error={questionError} ask={ask} />}</section></>
}

function Compare() { const [comparison, setComparison] = useState<Comparison | null>(null); const [error, setError] = useState(''); useEffect(() => { api.compare('demo-rental-v1', 'demo-rental-v2').then(setComparison).catch(() => setError('The comparison could not be loaded.')) }, []); return <><PageTitle eyebrow="Compare" title="See what changed." copy="Textual changes, side by side. Interpretation stays clearly labeled." action={<Link to="/app/documents/new" className="button secondary"><Plus size={17} /> Add document</Link>} />{error && <Feedback message={error} />}{!comparison && !error && <div className="loading-state" role="status"><span className="loader" /> Comparing documents...</div>}{comparison && <div className="comparison-results"><div className="comparison-header"><div><span className="section-label">{comparison.changes.length} changed clauses</span><h2>{comparison.title}</h2></div><span className="neutral-note"><ShieldCheck size={15} /> Text comparison only</span></div>{comparison.changes.map(change => <article className="change-card" key={change.heading}><div className="change-title"><span className="change-badge">Modified</span><h3>{change.heading}</h3><span>{change.summary}</span></div><div className="diff-grid"><div><span className="diff-label before">Original</span><p>{change.before}</p></div><div><span className="diff-label after">Revised</span><p>{change.after}</p></div></div></article>)}<div className="comparison-limit"><CircleHelp size={16} />{comparison.limitation}</div></div>}</> }
function NewDocument() { const navigate = useNavigate(); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const chooseFile = async (file: File | undefined) => { if (!file) return; setError(''); if (!['application/pdf', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'].includes(file.type) && !/\.(pdf|docx)$/i.test(file.name)) { setError('Choose a PDF or DOCX file.'); return } if (file.size > 10 * 1024 * 1024) { setError('Files must be smaller than 10 MB.'); return } setBusy(true); try { const document = await api.upload(file); navigate(`/app/documents/${document.id}`) } catch (uploadError) { setError(uploadError instanceof Error ? uploadError.message : 'Upload failed. Please try again.') } finally { setBusy(false) } }; return <><PageTitle eyebrow="New analysis" title="Bring a document into focus." copy="Upload a PDF or DOCX. Extracted text is kept page-aware and clearly labeled." /><div className="upload-layout"><div className="upload-card"><label className="upload-zone" htmlFor="document-upload"><span className="upload-icon"><Plus size={22} aria-hidden="true" /></span><h2>{busy ? 'Extracting text...' : 'Drop a document here'}</h2><p>PDF or DOCX · up to 10 MB</p><span className="button primary">{busy ? 'Working...' : 'Choose file'}</span><small>Files are validated by content signature on the server.</small><input id="document-upload" type="file" accept=".pdf,.docx,application/pdf,application/vnd.openxmlformats-officedocument.wordprocessingml.document" onChange={event => chooseFile(event.target.files?.[0])} disabled={busy} /></label>{error && <p className="upload-error" role="alert">{error}</p>}</div><div className="sample-options"><span className="section-label">Demo library</span><h2>Start with a sample</h2><p>These fictional agreements are labeled and safe to explore.</p><Link to={`/app/documents/${demoId}`} className="sample-option"><span className="file-icon"><FileText size={18} aria-hidden="true" /></span><span><b>Cedar Lane Rental Agreement</b><small>Rental · 3 pages · analyzed</small></span><ChevronRight size={16} aria-hidden="true" /></Link></div></div></> }
function Landing() { return <div className="landing"><header className="landing-nav"><div className="brand"><span className="brand-mark"><Sparkles size={16} aria-hidden="true" /></span><b>Nyaya<span>Lens</span></b></div><Link className="button ghost small" to="/app">Open workspace <ArrowRight size={15} aria-hidden="true" /></Link></header><main className="hero"><div className="hero-copy"><div className="eyebrow"><i /> Agreement review workspace</div><h1>Make dense agreements easier to act on.</h1><p>NyayaLens helps people review rental and other everyday agreements by extracting page-aware text, locating obligations, flagging missing details, comparing revisions, and answering questions with source clauses.</p><div className="hero-actions"><Link className="button primary" to="/app/documents/new">Review a document <ArrowRight size={17} aria-hidden="true" /></Link><Link className="text-link" to={`/app/documents/${demoId}`}>Explore the sample agreement <ChevronRight size={16} aria-hidden="true" /></Link></div><div className="hero-footnote"><ShieldCheck size={15} aria-hidden="true" /> Document text stays separate from interpretation. This is information support, not legal advice.</div></div><div className="hero-visual"><div className="paper"><div className="paper-head"><span>AGREEMENT REVIEW</span><span>01</span></div><div className="paper-line wide" /><div className="paper-line" /><div className="paper-highlight"><span>Review workflow</span><b>Clauses, obligations, flags, and questions in one place.</b></div><div className="paper-line wide" /><div className="paper-line shorter" /><div className="paper-footer"><span>Source-backed reading</span><span className="citation-badge">Page-aware</span></div></div><div className="floating-insight"><span><Flag size={15} aria-hidden="true" /></span><div><b>Attention flag</b><small>Notice delivery method is missing</small></div></div></div></main><section className="principles"><article><span className="section-label">01 · Find</span><h2>Locate the terms that matter.</h2><p>Search extracted clauses and trace every observation back to its page.</p></article><article><span className="section-label">02 · Understand</span><h2>Separate facts from interpretation.</h2><p>See explicit obligations alongside questions that deserve clarification.</p></article><article><span className="section-label">03 · Decide</span><h2>Prepare the next conversation.</h2><p>Compare revisions and export a concise action brief for human review.</p></article></section></div> }
function Settings() { return <><PageTitle eyebrow="Settings" title="Privacy and workspace." copy="Understand how this demo handles document data." /><div className="settings-grid"><section className="settings-card"><span className="section-label">Privacy notice</span><h2>Designed for sensitive reading</h2><p>This demo uses fictional fixtures and local persistence. Uploaded files are extracted by the API and are not sent to an external generative AI provider.</p></section></div></> }
function AppImproved() { return <BrowserRouter><Routes><Route path="/" element={<Landing />} /><Route path="/app" element={<Shell><Dashboard /></Shell>} /><Route path="/app/documents/new" element={<Shell><NewDocument /></Shell>} /><Route path="/app/documents/:documentId" element={<Shell><Workspace /></Shell>} /><Route path="/app/compare" element={<Shell><Compare /></Shell>} /><Route path="/app/settings" element={<Shell><Settings /></Shell>} /><Route path="*" element={<Shell><Empty title="Page not found" copy="The page you requested does not exist." /></Shell>} /></Routes></BrowserRouter> }
export default AppImproved
